import axios from 'axios';
import Head from 'next/head';
import Header from '../../components/Header';
import Sidebar from '../../components/Sidebar';

interface Data {
    isVerified: boolean;
    name: string;
    website: string;
    address: string;
    description: string;
    country: string;
}

export const getServerSideProps = async () => {
    let token = '';

    if (typeof window !== 'undefined') {
        token = localStorage.getItem('relief_work-token') || '';
    }

    if (!token) {
        return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        };
    }

    const res = await axios.get(`${process.env.NEXT_PUBLIC_API}/org`, {
        headers: { Authorization: `Bearer ${token}` },
    });

    const organizations: Data[] = res.data;

    if (!organizations) {
        return {
            notFound: true,
        };
    }

    return {
        props: {
            organizations,
        },
    };
};

const Organizations = ({ organizations }: { organizations: Data[] }) => (
    <div className="relative">
        <Head>
            <title>Relief Work | Organizations</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <main style={{ height: 'calc(100vh - 57px)' }} className="flex gap-5 pr-5 bg-gray-50">
            <Sidebar />

            {/* cards wrapper */}
            <div className="flex flex-col flex-1 gap-5 mt-5 mb-5 overflow-y-auto">
                {organizations.map((organization, index) => (
                    <div
                        // eslint-disable-next-line react/no-array-index-key
                        key={index}
                        className="flex flex-col max-w-xl gap-1 px-5 py-6 bg-white shadow-md rounded-xl"
                    >
                        <div className="flex flex-wrap items-center gap-2">
                            <span className="text-lg font-medium tracking-wide">
                                {organization.name}
                            </span>
                            <span className="text-sm tracking-wide text-gray-500">
                                ({organization.isVerified ? 'verified' : 'not verified'})
                            </span>
                        </div>

                        <div className="flex items-center gap-2">
                            <span className="font-medium text-gray-700">Website :</span>
                            <a
                                href={organization.website}
                                target="_blank"
                                rel="noreferrer"
                                className="text-sm italic tracking-wide text-blue-700"
                            >
                                visit the site
                            </a>
                        </div>

                        <div className="flex items-center gap-2">
                            <span className="font-medium text-gray-700">Country :</span>
                            <span className="text-sm tracking-wide text-gray-500">
                                {organization.country}
                            </span>
                        </div>

                        <div className="flex flex-wrap items-center gap-2">
                            <span className="font-medium text-gray-700">Address :</span>
                            <span className="text-sm tracking-wide text-gray-500">
                                {organization.address}
                            </span>
                        </div>

                        <p className="text-sm text-gray-600">{organization.description}</p>
                    </div>
                ))}
            </div>
        </main>
    </div>
);

export default Organizations;
