import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../../components/Header';
import Sidebar from '../../components/Sidebar';

const organizations = [
    {
        isVerified: false,
        name: 'test',
        website: 'http://google.com',
        address: 'test',
        description: 'test',
        country: 'Bangladesh',
    },
    {
        isVerified: false,
        name: 'test',
        website: 'http://google.com',
        address: 'test',
        description: 'test',
        country: 'Bangladesh',
    },
    {
        isVerified: false,
        name: 'test',
        website: 'http://google.com',
        address: 'test',
        description:
            'Ami onek boro programmer hoboi hobo Ami onek boro programmer hoboi hobo Ami onek boro programmer hoboi hobo',
        country: 'Bangladesh',
    },
    {
        isVerified: false,
        name: 'test',
        website: 'http://google.com',
        address: 'test',
        description: 'test',
        country: 'Bangladesh',
    },
    {
        isVerified: false,
        name: 'test',
        website: 'http://google.com',
        address: 'test',
        description: 'test',
        country: 'Bangladesh',
    },
    {
        isVerified: false,
        name: 'test',
        website: 'http://google.com',
        address: 'test',
        description:
            'Ami onek boro programmer hoboi hobo Ami onek boro programmer hoboi hobo Ami onek boro programmer hoboi hobo',
        country: 'Bangladesh',
    },
];

const Organizations: NextPage = () => (
    <div className="relative">
        <Head>
            <title>Relief Work | Organizations</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <main style={{ height: 'calc(100vh - 57px)' }} className="bg-gray-50 flex gap-5 pr-5">
            <Sidebar />

            {/* cards wrapper */}
            <div className="mt-5 mb-5 flex-1 flex gap-5 flex-col overflow-y-auto">
                {organizations.map((organization, index) => (
                    <div
                        // eslint-disable-next-line react/no-array-index-key
                        key={index}
                        className="bg-white rounded-xl flex flex-col gap-1 py-6 px-5 shadow-md max-w-xl"
                    >
                        <div className="flex gap-2 items-center flex-wrap">
                            <span className="text-lg font-medium tracking-wide">
                                {organization.name}
                            </span>
                            <span className="text-gray-500 text-sm tracking-wide">
                                ({organization.isVerified ? 'verified' : 'not verified'})
                            </span>
                        </div>

                        <div className="flex gap-2 items-center">
                            <span className="text-gray-700 font-medium">Website :</span>
                            <a
                                href={organization.website}
                                target="_blank"
                                rel="noreferrer"
                                className="text-blue-700 tracking-wide italic text-sm"
                            >
                                visit the site
                            </a>
                        </div>

                        <div className="flex gap-2 items-center">
                            <span className="text-gray-700 font-medium">Country :</span>
                            <span className="text-gray-500 tracking-wide text-sm">
                                {organization.country}
                            </span>
                        </div>

                        <div className="flex gap-2 items-center flex-wrap">
                            <span className="text-gray-700 font-medium">Address :</span>
                            <span className="text-gray-500 tracking-wide text-sm">
                                {organization.address}
                            </span>
                        </div>

                        <p className="text-gray-600 text-sm">{organization.description}</p>
                    </div>
                ))}
            </div>
        </main>
    </div>
);

export default Organizations;
