import { yupResolver } from '@hookform/resolvers/yup/dist/yup';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { toast } from 'react-toastify';
import { logInUser } from '../../apiHandlers/auth';
import Loader from '../../components/Loader';
import TextField from '../../components/TextField';
import fields from '../../utils/LoginFormFields';
import schema from '../../utils/LoginFormSchema';

export interface LoginData {
    phone: string;
    password: string;
}

const Login: NextPage = () => {
    const router = useRouter();

    const [isLoading, setIsLoading] = useState(false);

    const {
        register,
        handleSubmit,
        formState: { errors },
    } = useForm({
        resolver: yupResolver(schema),
    });

    useEffect(() => {
        toast.warn('Please login or register an account', { autoClose: 3000 });
    }, []);

    const submitForm = async (data: LoginData) => {
        setIsLoading(true);

        const { loggedIn } = await logInUser(data);

        setIsLoading(false);

        if (loggedIn) {
            router.push('/');
            toast.success('Logged in successfully', { autoClose: 3000 });
        } else {
            toast.error('Unauthorized', { autoClose: 3000 });
        }
    };

    return (
        <div>
            <Head>
                <title>Relief Work | Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* loader */}
            {isLoading ? <Loader /> : null}

            <main
                className="flex items-center justify-center h-screen"
                style={{ backgroundImage: 'url("/background.jpg")' }}
            >
                <div className="flex flex-col items-center px-8 pt-6 pb-8 mb-4 bg-white rounded-lg shadow-md">
                    {/* form header */}
                    <div className="flex flex-col items-center gap-4 mb-6">
                        <h1 className="text-2xl font-medium tracking-wide">
                            Login to your account
                        </h1>
                        <p className="text-sm font-medium text-gray-500">
                            Don&#39;t have a profile yet?{' '}
                            <span className="text-blue-600 transition-colors hover:text-blue-500">
                                <Link href="/register/organization-info">Register</Link>
                            </span>
                        </p>
                    </div>

                    {/* form body */}
                    <form
                        className="flex flex-col items-end gap-5"
                        onSubmit={handleSubmit(submitForm)}
                    >
                        <div className="flex flex-col">
                            {fields.map((field) => (
                                <TextField
                                    key={field.name}
                                    label={field.label}
                                    type={field.type}
                                    placeholder={field.placeholder}
                                    name={field.name}
                                    className="mt-4 md:w-96"
                                    error={errors[field.name]?.message}
                                    register={register}
                                />
                            ))}
                        </div>

                        <button
                            type="submit"
                            className="px-4 py-2 text-base font-semibold text-gray-100 bg-green-700 rounded-md hover:text-white hover:bg-green-500 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-green-800 focus:ring-offset-2"
                        >
                            Login
                        </button>
                    </form>
                </div>
            </main>
        </div>
    );
};

export default Login;
