import { yupResolver } from '@hookform/resolvers/yup/dist/yup';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useForm } from 'react-hook-form';
import { useDispatch, useSelector } from 'react-redux';
import TextField from '../../components/TextField';
import { setOrgInfo } from '../../store/rootSlice';
import { RootState } from '../../store/store';
import fields from '../../utils/RegFormFields';
import schema from '../../utils/RegFormSchema';

interface FormData {
    orgName: string;
    website: string;
    country: string;
    orgAddress: string;
    description: string;
}

const Register: NextPage = () => {
    const router = useRouter();
    const dispatch = useDispatch();
    const registrationData = useSelector<RootState, RootState>((state) => state);

    const {
        register,
        handleSubmit,
        formState: { errors },
    } = useForm({
        resolver: yupResolver(schema.orgInfo),
        defaultValues: {
            orgName: registrationData.org.name,
            website: registrationData.org.website,
            country: registrationData.org.country,
            orgAddress: registrationData.org.address,
            description: registrationData.org.description,
        },
    });

    const submitForm = (data: FormData) => {
        console.log(data);

        dispatch(setOrgInfo(data));
        router.push('/register/personal-info');
    };

    return (
        <div>
            <Head>
                <title>Relief Work | Registration</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main
                className="min-h-screen flex items-center justify-center md:py-0 py-12"
                style={{ backgroundImage: 'url("/background.jpg")' }}
            >
                <div className="flex flex-col items-center px-8 pt-6 pb-8 rounded-lg shadow-md bg-white">
                    {/* form header */}
                    <div className="mb-6 flex flex-col items-center gap-4">
                        <h1 className="text-2xl font-medium tracking-wide">Register an account</h1>
                        <p className="text-sm text-gray-500 font-medium">
                            Already have an account?{' '}
                            <span className="text-blue-600 hover:text-blue-500 transition-colors">
                                <Link href="/login">Login</Link>
                            </span>
                        </p>
                    </div>

                    {/* form body */}
                    <form
                        className="flex flex-col items-end gap-5"
                        onSubmit={handleSubmit(submitForm)}
                    >
                        <div>
                            <h3 className="-mb-2 text-xs italic text-gray-400">
                                Organization Information
                            </h3>

                            {fields.orgInfo.map((field) => (
                                <TextField
                                    key={field.name}
                                    label={field.label}
                                    type={field.type}
                                    placeholder={field.placeholder}
                                    name={field.name}
                                    className="mt-4 md:w-96"
                                    // @ts-ignore
                                    error={errors[field.name]?.message}
                                    register={register}
                                />
                            ))}
                        </div>

                        <button
                            type="submit"
                            className="px-4 py-2 text-base font-semibold text-gray-100 bg-green-700 rounded-md hover:text-white hover:bg-green-500 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-green-800 focus:ring-offset-2"
                        >
                            Next
                        </button>
                    </form>
                </div>
            </main>
        </div>
    );
};

export default Register;
