import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import Header from '../components/Header';
import Loader from '../components/Loader';
import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
    const router = useRouter();

    const [isLoading, setIsLoading] = useState(false);

    useEffect(() => {
        const apiResponse = async () => {
            const token = localStorage.getItem('relief_work-token') || '';

            if (!token) {
                router.push('/login');
            }

            try {
                setIsLoading(true);

                const res = await axios.get(`${process.env.NEXT_PUBLIC_API}/auth/me`, {
                    headers: { Authorization: `Bearer ${token}` },
                });

                if (res) {
                    setIsLoading(false);
                }
            } catch (err) {
                setIsLoading(false);
                toast.warn('Please login or register an account', { autoClose: 3000 });
                console.log(err);
                router.push('/login');
            }
        };
        apiResponse();
    }, [router]);

    return (
        <div className="relative">
            <Head>
                <title>Relief Work | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* loader */}
            {isLoading ? <Loader /> : null}

            <Header />

            <main className="bg-gray-50">
                <Sidebar />
            </main>
        </div>
    );
};

export default Home;
