import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
    <div className="relative">
        <Head>
            <title>Relief Work | Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>Relief Work</main>
    </div>
);

export default Home;
