import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';

const Home: NextPage = () => (
    <div className="relative">
        <Head>
            <title>Relief Work | Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <main className="bg-gray-50">
            <Sidebar />
        </main>
    </div>
);

export default Home;
