const fields = [
    {
        label: 'Organization Name',
        type: 'text',
        name: 'orgName',
        placeholder: 'Organization Name',
        forCreate: true,
        forUpdate: true,
    },
    {
        label: 'Title',
        type: 'text',
        name: 'title',
        placeholder: 'Title',
        forCreate: true,
        forUpdate: true,
    },
    {
        label: 'Status',
        type: 'text',
        name: 'status',
        placeholder: 'Status',
        forUpdate: true,
    },
    {
        label: 'District',
        type: 'text',
        name: 'district',
        placeholder: 'District',
        forCreate: true,
        forUpdate: true,
    },
    {
        label: 'Thana',
        type: 'text',
        name: 'thana',
        placeholder: 'Thana',
        forCreate: true,
        forUpdate: true,
    },
    {
        label: 'Venue',
        type: 'text',
        name: 'venue',
        placeholder: 'Venue',
        forCreate: true,
        forUpdate: true,
    },
    {
        label: 'Event Start Date',
        type: 'date',
        name: 'eventStartDate',
        placeholder: 'Event Start Date',
        forCreate: true,
        forUpdate: true,
    },
    {
        label: 'Event End Date',
        type: 'date',
        name: 'eventEndDate',
        placeholder: 'Event End Date',
        forCreate: true,
        forUpdate: true,
    },
    {
        label: 'Description',
        type: 'textarea',
        name: 'description',
        placeholder: 'Description',
        forCreate: true,
        forUpdate: true,
    },
];

export default fields;
